### ISSUE TITLE
Add me as a collaborator

### ISSUE THREAD

**Issue by rollinger** [Almendri/Excercises#1]
Please add me as a collaborator and change my access rights to admin, so I can help you better.
If you completed this, please comment on this issue and close the issue as "completed"

PS: Asi vamos a trabajar junto. Las tareas van a ser en ingles (la lengua principal de programmacion). Si algo no esta claro, siempre puedes escribir un comentario en el issue. Te recomiendo tambien usar ingles cuando puedes. Al principio sera un poco mas dificil, pero en el largo plazo te ayudará mucho.

**Comment by Almendri** [comment]
Si, también practicare mas ingles. Y tarea resuelta, ya lo he agregado como colaborador.

**Comment by rollinger** [comment]
Muy bien Sofia! 

You can close the issue now.
